<a href="https://colab.research.google.com/github/jiteshchandra80/heartdisease/blob/new_branch/email_classify.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [8]:
from google.colab import files
uploaded=files.upload()

In [0]:
df=pd.read_csv("emails.csv")

In [10]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [11]:
df.shape

(5728, 2)

In [12]:
df.drop_duplicates(inplace=True)
df.shape

(5695, 2)

In [13]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [17]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
def process_text(text):
    '''
    What will be covered:
    1. Remove punctuation
    2. Remove stopwords
    3. Return list of clean text words
    '''
    
    #1
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    #2
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    #3
    return clean_words

In [19]:
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [20]:
mess4="play play play you want to have play"
mess5="test test test one test for you"
print(mess4)
print()

#. converting text to the matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
tok=CountVectorizer(analyzer=process_text).fit_transform([[mess4],[mess5]])
print(tok)
print("\n\n")

print(tok.shape)


play play play you want to have play

  (0, 1)	4
  (0, 3)	1
  (1, 2)	4
  (1, 0)	1



(2, 4)


In [0]:
from sklearn.feature_extraction.text import CountVectorizer
newword=CountVectorizer(analyzer=process_text).fit_transform(df["text"])

In [0]:
#spiliting the dataset into training and testing
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(newword,df["spam"],test_size=0.2,random_state=0)

In [0]:
# making a naive bayes to apply the machine learnning algorithm
from sklearn.naive_bayes import MultinomialNB
classify=MultinomialNB().fit(train_x,train_y)

In [29]:
print(classify.predict(train_x))
print(train_y.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [32]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
pred=classify.predict(train_x)
print("Classification report : ",classification_report(pred,train_y))
print("\n\n")
print("Confusion matrix is :",confusion_matrix(pred,train_y))
print("")
print("The accuracy is :",accuracy_score(pred,train_y))

Classification report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00      3446
           1       1.00      0.99      0.99      1110

    accuracy                           1.00      4556
   macro avg       1.00      0.99      1.00      4556
weighted avg       1.00      1.00      1.00      4556




Confusion matrix is : [[3445    1]
 [  12 1098]]

The accuracy is : 0.9971466198419666


In [35]:
#Now workiing for the testing data
print(classify.predict(test_x))
print(test_y.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [36]:
# Now calculating the report for the testing data
pred=classify.predict(test_x)
print("Classification report : ",classification_report(pred,test_y))
print("\n\n")
print("Confusion matrix is :",confusion_matrix(pred,test_y))
print("")
print("The accuracy is :",accuracy_score(pred,test_y))

Classification report :                precision    recall  f1-score   support

           0       0.99      1.00      0.99       863
           1       1.00      0.97      0.98       276

    accuracy                           0.99      1139
   macro avg       0.99      0.98      0.99      1139
weighted avg       0.99      0.99      0.99      1139




Confusion matrix is : [[862   1]
 [  8 268]]

The accuracy is : 0.9920983318700615
